#!/usr/bin/env python3
"""confluence_sync.py — flows.json -> Confluence pages (prose + Mermaid).

Renders each flow to a Confluence page: plain-language prose, a Mermaid
sequence diagram of the same steps, a link to the interactive living doc, and
a release note. Pages are upserted through the REST API and tracked in
code2docs/.confluence_map.json (flowId -> pageId). Every page gets a
`code2docs-review` label (and, if configured, a dedicated parent page) so
nothing goes live unreviewed.

If the CONFLUENCE_* environment variables are absent (or --dry-run is given)
it does NOT call the network — it writes the exact storage-format body it
*would* publish to code2docs/.confluence_preview/ so the pipeline is fully
runnable offline and in CI without secrets.

Env: CONFLUENCE_BASE_URL, CONFLUENCE_USER, CONFLUENCE_API_TOKEN, CONFLUENCE_SPACE_KEY

Usage:
    python code2docs/confluence_sync.py                 # all flows
    python code2docs/confluence_sync.py --only impacted.json
    python code2docs/confluence_sync.py --dry-run       # force offline preview
"""

from __future__ import annotations

import argparse
import base64
import html
import json
import os
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

import c2d_common as c2d


# ---- rendering -----------------------------------------------------------

def mermaid_diagram(flow: dict, version: str) -> str:
    """A Mermaid sequenceDiagram string mirroring the flow's steps."""
    lines = ["sequenceDiagram", "    autonumber"]
    for i, a in enumerate(flow.get("actors", [])):
        name = f"{a.get('emoji','')} {a['name']}".strip()
        lines.append(f'    participant P{i} as "{name}"')
    for s in flow.get("steps", []):
        cap = s.get("cap", "")
        tag = ""
        if s.get("since") == version:
            tag = f"  🆕 new in {version}"
        elif s.get("changed"):
            tag = "  ✏️ changed"
        arrow = "->>" if s["from"] != s["to"] else "-)"
        lines.append(f'    P{s["from"]}{arrow}P{s["to"]}: {mm_escape(cap)}{tag}')
    return "\n".join(lines)


def mm_escape(text: str) -> str:
    return text.replace(":", " ").replace("\n", " ").strip()


def storage_body(flow: dict, doc: dict, cfg: dict) -> str:
    """Confluence storage-format (XHTML) body for one flow."""
    version = c2d.short_version(doc.get("version", ""))
    esc = html.escape
    parts = []

    desc = flow.get("description") or f"An automatically narrated walkthrough of “{flow.get('title')}”."
    parts.append(f"<p><em>{esc(desc)}</em></p>")

    # interactive link
    base = cfg.get("interactive_base_url", "").rstrip("/")
    if base:
        parts.append(f'<p><a href="{esc(base)}/{flow["id"]}.html">▶ Open the interactive living doc</a></p>')

    # release highlight callout
    added = [s for s in flow["steps"] if s.get("since") == version]
    changed = [s for s in flow["steps"] if s.get("changed")]
    if added or changed:
        items = "".join(f"<li>🆕 new: {esc(s.get('cap',''))}</li>" for s in added) + \
                "".join(f"<li>✏️ changed: {esc(s.get('cap',''))}</li>" for s in changed)
        parts.append(
            '<ac:structured-macro ac:name="info"><ac:rich-text-body>'
            f"<p><strong>What changed in v{esc(version)}</strong></p><ul>{items}</ul>"
            "</ac:rich-text-body></ac:structured-macro>")

    # mermaid sequence diagram
    macro = cfg.get("mermaid_macro", "code")
    diagram = mermaid_diagram(flow, version)
    if macro == "code":
        parts.append(
            '<ac:structured-macro ac:name="code">'
            '<ac:parameter ac:name="language">mermaid</ac:parameter>'
            f"<ac:plain-text-body><![CDATA[{diagram}]]></ac:plain-text-body>"
            "</ac:structured-macro>")
    else:
        parts.append(
            f'<ac:structured-macro ac:name="{esc(macro)}">'
            f"<ac:plain-text-body><![CDATA[{diagram}]]></ac:plain-text-body>"
            "</ac:structured-macro>")

    # prose walkthrough
    parts.append("<h2>Step by step</h2><ol>")
    for s in flow["steps"]:
        badge = ""
        if s.get("since") == version:
            badge = f' <ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">Green</ac:parameter><ac:parameter ac:name="title">new in {esc(version)}</ac:parameter></ac:structured-macro>'
        elif s.get("changed"):
            badge = ' <ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">Yellow</ac:parameter><ac:parameter ac:name="title">changed</ac:parameter></ac:structured-macro>'
        parts.append(f"<li>{esc(s.get('say', s.get('cap','')))}{badge}"
                     f"<br/><code>{esc(s.get('tech',''))}</code></li>")
    parts.append("</ol>")

    parts.append(f"<hr/><p><sub>Generated by Code2Docs from the code graph "
                 f"(module {esc(doc.get('module',''))}, v{esc(doc.get('version',''))}). "
                 f"Review before publishing.</sub></p>")
    return "".join(parts)


def page_title(flow: dict, doc: dict, cfg: dict) -> str:
    prefix = cfg.get("title_prefix", "")
    return f"{prefix}{doc.get('module','')} — {flow.get('title', flow['id'])}"


# ---- Confluence REST (stdlib only) --------------------------------------

class Confluence:
    def __init__(self, base, user, token, space):
        self.base = base.rstrip("/")
        self.space = space
        auth = base64.b64encode(f"{user}:{token}".encode()).decode()
        self.headers = {"Authorization": f"Basic {auth}",
                        "Content-Type": "application/json", "Accept": "application/json"}

    def _req(self, method, path, payload=None):
        url = path if path.startswith("http") else f"{self.base}/rest/api{path}"
        data = json.dumps(payload).encode() if payload is not None else None
        req = urllib.request.Request(url, data=data, headers=self.headers, method=method)
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode() or "{}")

    def get_page(self, page_id):
        return self._req("GET", f"/content/{page_id}?expand=version")

    def find_by_title(self, title):
        """Existing page with this title in the space, or None. Lets a run
        whose page map is stale (docs PR not merged yet) update instead of
        creating a duplicate title, which Confluence rejects with a 400."""
        q = urllib.parse.urlencode({"spaceKey": self.space, "title": title,
                                    "expand": "version"})
        results = self._req("GET", f"/content?{q}").get("results", [])
        return results[0] if results else None

    def create(self, title, body, parent_id=None):
        payload = {"type": "page", "title": title, "space": {"key": self.space},
                   "body": {"storage": {"value": body, "representation": "storage"}}}
        if parent_id:
            payload["ancestors"] = [{"id": str(parent_id)}]
        return self._req("POST", "/content", payload)

    def update(self, page_id, title, body, next_version):
        payload = {"id": page_id, "type": "page", "title": title,
                   "space": {"key": self.space},
                   "version": {"number": next_version},
                   "body": {"storage": {"value": body, "representation": "storage"}}}
        return self._req("PUT", f"/content/{page_id}", payload)

    def add_label(self, page_id, label):
        try:
            self._req("POST", f"/content/{page_id}/label", [{"prefix": "global", "name": label}])
        except urllib.error.HTTPError:
            pass


def main():
    ap = argparse.ArgumentParser(description="Sync flows to Confluence (prose + Mermaid).")
    ap.add_argument("--config", default=None)
    ap.add_argument("--flows", default=None)
    ap.add_argument("--only", default=None, help="impacted.json: only sync these flow ids")
    ap.add_argument("--dry-run", action="store_true", help="force offline preview, never call the network")
    args = ap.parse_args()

    c2d.init_io()
    cfg = c2d.load_config(args.config)
    ccfg = cfg.get("confluence", {})
    flows_path = Path(args.flows) if args.flows else c2d._abs(cfg["flows_path"])
    doc = json.loads(flows_path.read_text(encoding="utf-8"))
    flows = doc.get("flows", [])

    only = None
    if args.only:
        only = set(json.loads(Path(args.only).read_text(encoding="utf-8")).get("flows", []))
    targets = [f for f in flows if only is None or f["id"] in only]

    base = os.environ.get("CONFLUENCE_BASE_URL")
    user = os.environ.get("CONFLUENCE_USER")
    token = os.environ.get("CONFLUENCE_API_TOKEN")
    space = os.environ.get("CONFLUENCE_SPACE_KEY")
    live = all([base, user, token, space]) and not args.dry_run

    # merge interactive base into confluence render config
    ccfg = dict(ccfg)
    ccfg.setdefault("interactive_base_url", cfg.get("interactive_base_url", ""))

    map_path = c2d._abs(cfg["confluence_map_path"])
    cmap = json.loads(map_path.read_text(encoding="utf-8")) if map_path.exists() else {}

    if not live:
        preview_dir = c2d._abs(ccfg.get("preview_dir", "code2docs/.confluence_preview"))
        preview_dir.mkdir(parents=True, exist_ok=True)
        reason = "--dry-run" if args.dry_run else "CONFLUENCE_* env not set"
        print(f"[dry-run: {reason}] writing storage-format previews to {preview_dir}")
        for f in targets:
            body = storage_body(f, doc, ccfg)
            title = page_title(f, doc, ccfg)
            out = preview_dir / f"{f['id']}.html"
            out.write_text(f"<!-- {title} -->\n<!-- label: {ccfg.get('review_label')} -->\n{body}",
                           encoding="utf-8")
            print(f"  - {f['id']:30s} -> {out.name}  ({len(body)} chars)")
        print(f"\n{len(targets)} page(s) previewed. Set CONFLUENCE_* env to publish for real.")
        return

    api = Confluence(base, user, token, space)
    parent = ccfg.get("parent_page_id") or None
    label = ccfg.get("review_label", "code2docs-review")
    synced, failed = 0, 0
    for f in targets:
        title = page_title(f, doc, ccfg)
        body = storage_body(f, doc, ccfg)
        try:
            pid = cmap.get(f["id"])
            if not pid:
                # Self-heal a stale map: the page may already exist from a run
                # whose docs PR (carrying the map update) was never merged.
                existing = api.find_by_title(title)
                if existing:
                    pid = existing["id"]
                    cmap[f["id"]] = pid
                    print(f"  map healed: {f['id']} -> existing page {pid}")
            if pid:
                cur = api.get_page(pid)
                api.update(pid, title, body, cur["version"]["number"] + 1)
                print(f"  updated {f['id']} -> page {pid}")
            else:
                created = api.create(title, body, parent)
                pid = created["id"]
                cmap[f["id"]] = pid
                print(f"  created {f['id']} -> page {pid}")
            api.add_label(pid, label)
            synced += 1
        except urllib.error.HTTPError as e:
            failed += 1
            try:
                detail = e.read().decode("utf-8", errors="replace")[:300]
            except Exception:
                detail = ""
            print(f"::warning::Confluence sync failed for {f['id']}: "
                  f"HTTP {e.code} {e.reason} {detail}")

    # Persist whatever we learned (created ids, healed entries) even if some
    # pages failed, so the next run doesn't repeat the same create attempts.
    map_path.write_text(json.dumps(cmap, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nSynced {synced}/{len(targets)} page(s), {failed} failed. Map -> {map_path}")


if __name__ == "__main__":
    main()
