#!/usr/bin/env python3
"""render_release_digest.py — diff -> plain-English "what changed" notes.

Reads the (already-highlighted) flows.json and impacted.json and writes a
human-readable release digest to docs/RELEASE_NOTES.md, newest entry on top.
This is the surface a PM or support engineer reads to learn, in one paragraph
per flow, what a merge actually changed about the product's behaviour.

Usage:
    python code2docs/render_release_digest.py changed.txt
    python code2docs/render_release_digest.py changed.txt --pr 123 --version 3.11 --date "2 Jul 2026"
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import c2d_common as c2d

_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def today_str() -> str:
    d = datetime.now(timezone.utc)
    return f"{d.day} {_MONTHS[d.month - 1]} {d.year}"


def main():
    ap = argparse.ArgumentParser(description="Render a plain-English release digest.")
    ap.add_argument("changed", nargs="?", help="changed.txt (repo-relative paths)")
    ap.add_argument("--config", default=None)
    ap.add_argument("--impacted", default=None, help="impacted.json (default code2docs/impacted.json)")
    ap.add_argument("--flows", default=None)
    ap.add_argument("--version", default=None)
    ap.add_argument("--date", default=None)
    ap.add_argument("--pr", default=None, help="PR number for the heading")
    ap.add_argument("--out", default=None, help="release notes path")
    ap.add_argument("--bootstrap", action="store_true",
                    help="seed the initial catalog entry from all flows (no diff)")
    args = ap.parse_args()

    c2d.init_io()
    cfg = c2d.load_config(args.config)
    version = args.version or c2d.short_version(c2d.read_version(cfg))
    date = args.date or today_str()

    flows_path = Path(args.flows) if args.flows else c2d._abs(cfg["flows_path"])
    doc = json.loads(flows_path.read_text(encoding="utf-8"))
    flows_by_id = {f["id"]: f for f in doc.get("flows", [])}

    imp_path = Path(args.impacted) if args.impacted else c2d.REPO_ROOT / "code2docs" / "impacted.json"
    impacted = json.loads(imp_path.read_text(encoding="utf-8")) if imp_path.exists() else {}
    impacted_ids = impacted.get("flows", [])
    module_files = impacted.get("moduleChangedFiles", [])
    if not module_files and args.changed and Path(args.changed).exists():
        module_files = [l.strip() for l in Path(args.changed).read_text(encoding="utf-8").splitlines() if l.strip()]

    if args.bootstrap:
        entry = build_bootstrap(cfg, version, date, doc.get("flows", []))
    else:
        entry = build_entry(cfg, version, date, args.pr, impacted_ids, flows_by_id, module_files)

    out_path = Path(args.out) if args.out else c2d._abs(cfg["release_notes"])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = f"# {cfg['module_name']} — Release Digest\n\n" \
             "_Plain-English summary of what each merge changed, generated by Code2Docs._\n"
    prior = ""
    if out_path.exists():
        text = out_path.read_text(encoding="utf-8")
        # strip the standing header so we can re-emit it on top of the newest entry
        prior = text.split("\n", 3)[-1] if text.startswith("# ") else text
    out_path.write_text(header + "\n" + entry + ("\n" + prior if prior.strip() else ""), encoding="utf-8")

    print(f"Wrote release digest -> {out_path}")
    print(f"  v{version} · {date} · {len(impacted_ids)} impacted flow(s)")


def build_entry(cfg, version, date, pr, impacted_ids, flows_by_id, module_files) -> str:
    pr_txt = f"  (PR #{pr})" if pr else ""
    lines = [f"## v{version} — {date}{pr_txt}", ""]

    if not impacted_ids:
        lines.append("_No documented user flow changed in this merge._")
        if module_files:
            lines.append("")
            lines.append("**Files changed in this module:** " + ", ".join(f"`{f}`" for f in module_files))
        lines.append("")
        lines.append("<sub>Generated by Code2Docs from the code graph.</sub>")
        lines.append("\n---\n")
        return "\n".join(lines)

    n_new = n_chg = 0
    body = []
    internals_only = []
    for fid in impacted_ids:
        flow = flows_by_id.get(fid)
        if not flow:
            continue
        added = [s for s in flow["steps"] if s.get("since") == version]
        changed = [s for s in flow["steps"] if s.get("changed")]
        if not added and not changed:
            internals_only.append(flow.get("title", fid))
            continue
        n_new += len(added)
        n_chg += len(changed)
        body.append(f"### {flow.get('title', fid)}")
        for s in added:
            body.append(f"- 🆕 New step — the assistant now also {phrase(s)} "
                        f"<sub>({s.get('cap','')})</sub>.")
        for s in changed:
            verb = "no longer" if s.get("removed") else "changed how it"
            body.append(f"- ✏️ Changed — {verb} {phrase(s)} <sub>({s.get('cap','')})</sub>.")
        crosses = ", ".join(a["name"] for a in flow.get("actors", []) if a.get("name") != "You")
        if crosses:
            body.append(f"- _Touches:_ {crosses}.")
        body.append("")

    if internals_only:
        body.append(f"**Also re-checked (no visible flow change):** "
                    + ", ".join(internals_only) + ".")
        body.append("")

    changed_flows = len(impacted_ids) - len(internals_only)
    summary = (f"**{changed_flows} flow(s) visibly changed** — "
               f"{n_new} new step(s), {n_chg} changed"
               + (f"; {len(internals_only)} more re-checked." if internals_only else "."))
    interactive = f"[▶ Open the interactive living docs]({rel_interactive(cfg)})"
    lines += [summary, "", interactive, ""]
    lines += body
    if module_files:
        lines.append("**Files changed in this module:** " + ", ".join(f"`{f}`" for f in module_files))
        lines.append("")
    lines.append("<sub>Generated by Code2Docs from the code graph — review before publishing.</sub>")
    lines.append("\n---\n")
    return "\n".join(lines)


def build_bootstrap(cfg, version, date, flows) -> str:
    lines = [f"## v{version} — {date}  (initial documentation)", "",
             f"**Code2Docs is now live for {cfg['module_name']}.** "
             f"{len(flows)} flow(s) documented as interactive living docs.", "",
             f"[▶ Open the interactive living docs]({rel_interactive(cfg)})", ""]
    for f in flows:
        desc = f.get("description", "")
        lines.append(f"- **{f.get('title', f['id'])}** — {desc}")
    lines += ["", "<sub>Generated by Code2Docs from the code graph. Future merges "
              "will append what each one changed.</sub>", "\n---\n"]
    return "\n".join(lines)


def phrase(step: dict) -> str:
    """Lower-cased action phrase without trailing period, for inline prose."""
    say = (step.get("say") or step.get("cap") or "").strip()
    # drop a leading "Component: " handoff prefix for the prose form
    if ": " in say and say.split(": ", 1)[0][0:1].isupper() and len(say.split(": ", 1)[0]) < 40:
        say = say.split(": ", 1)[1]
    say = say.rstrip(".")
    return say[0].lower() + say[1:] if say else "runs new logic"


def rel_interactive(cfg) -> str:
    # release notes live in docs/, interactive in docs/interactive/
    out = cfg.get("interactive_out", "docs/interactive").replace("docs/", "")
    return f"{out}/index.html"


if __name__ == "__main__":
    main()
